name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
            root_file: 00_Article_Merge.tex
    - name: Move files
      run: |
        mkdir ./pdf
        mv ./00_Article_Merge.pdf ./pdf/Article.pdf
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./pdf
        force_orphan: true
