name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Compile LaTeX document
#      uses:  truatpasteurdotfr/latex-action@v0.0.0-alpha
      uses:  xu-cheng/latex-action@v2
      with:
            root_file: Article.tex
            working_directory: latex
    - name: Move files
      run: |
        mkdir ./pdf
        mv ./latex/Article.pdf ./pdf/Article.pdf
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./pdf
        force_orphan: true
